/**
 * GTS
 * Gift tracking 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeModelResponse } from './attributeModelResponse';


export interface EntityModelActionResponse { 
    id: string;
    displayNames: { [key: string]: string; };
    attributeModels: Array<AttributeModelResponse>;
    type: EntityModelActionResponse.TypeEnum;
    icon?: string;
    roles?: Array<string>;
    formMode: EntityModelActionResponse.FormModeEnum;
}
export namespace EntityModelActionResponse {
    export type TypeEnum = 'UPDATE' | 'CREATE';
    export const TypeEnum = {
        UPDATE: 'UPDATE' as TypeEnum,
        CREATE: 'CREATE' as TypeEnum
    };
    export type FormModeEnum = 'VIEW' | 'EDIT' | 'BOTH';
    export const FormModeEnum = {
        VIEW: 'VIEW' as FormModeEnum,
        EDIT: 'EDIT' as FormModeEnum,
        BOTH: 'BOTH' as FormModeEnum
    };
}


