/**
 * GTS
 * Gift tracking 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterModel } from './filterModel';


export interface InstantRangeFilterModel extends FilterModel { 
    from?: string;
    to?: string;
}
export namespace InstantRangeFilterModel {
}


