/**
 * GTS
 * Gift tracking 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterModel } from './filterModel';


export interface NotFilterModel extends FilterModel { 
    filter: FilterModel;
}
export namespace NotFilterModel {
}


