/**
 * GTS
 * Gift tracking 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateRangeFilterModel } from './dateRangeFilterModel';
import { ElementCollectionFilterModel } from './elementCollectionFilterModel';
import { LocalTime } from './localTime';
import { NullFilterModel } from './nullFilterModel';
import { NumberInFilterModel } from './numberInFilterModel';
import { OrFilterModel } from './orFilterModel';
import { InstantRangeFilterModel } from './instantRangeFilterModel';
import { NumberRangeFilterModel } from './numberRangeFilterModel';
import { FilterModel } from './filterModel';
import { TimeRangeFilterModel } from './timeRangeFilterModel';
import { LocalDateTimeRangeFilterModel } from './localDateTimeRangeFilterModel';
import { EqualsFilterModel } from './equalsFilterModel';
import { NotFilterModel } from './notFilterModel';


/**
 * @type SearchModelFiltersInner
 * @export
 */
export type SearchModelFiltersInner = DateRangeFilterModel | ElementCollectionFilterModel | EqualsFilterModel | InstantRangeFilterModel | LocalDateTimeRangeFilterModel | NotFilterModel | NullFilterModel | NumberInFilterModel | NumberRangeFilterModel | OrFilterModel | TimeRangeFilterModel;

